spring.application.name=prep-api
server.port=8080

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:interview_prep_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:prakhar123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA Automations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${JWT_SECRET:dummy_secret_key_for_local_dev_only_1234567890_change_me}
app.jwt.expirationMs=86400000